import { InventoryItem, NGO, Customer, ExpiryTrendData, CategoryBreakdown, ActivityLog } from "@/types";

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: "INV-8091",
    sku: "DY-9921",
    name: "Organic Whole Milk 1L",
    category: "Dairy & Eggs",
    quantity: 140,
    unit: "Cartons",
    unitPrice: 3.50,
    totalValue: 490,
    expiryDate: "2026-07-26", // <2 days
    location: "Aisle A4 - Cold Unit 2",
    supplier: "Green Pastures Farm",
    status: "critical",
    isDispatched: false,
  },
  {
    id: "INV-8092",
    sku: "PR-3312",
    name: "Hass Avocado Pack (4pcs)",
    category: "Fresh Produce",
    quantity: 85,
    unit: "Packs",
    unitPrice: 4.80,
    totalValue: 408,
    expiryDate: "2026-07-27", // <3 days
    location: "Produce Bay 1",
    supplier: "Fresh Harvest Co",
    status: "critical",
    isDispatched: false,
  },
  {
    id: "INV-8093",
    sku: "BK-1044",
    name: "Artisan Sourdough Loaves",
    category: "Bakery & Deli",
    quantity: 60,
    unit: "Loaves",
    unitPrice: 5.20,
    totalValue: 312,
    expiryDate: "2026-07-25", // tomorrow
    location: "Bakery Rack B",
    supplier: "Daily Crust Bakery",
    status: "critical",
    isDispatched: true,
    rescuedByNGO: "Metro Harvest Food Bank",
  },
  {
    id: "INV-8094",
    sku: "ME-5510",
    name: "Grass-Fed Beef Mince 500g",
    category: "Meat & Seafood",
    quantity: 45,
    unit: "Packs",
    unitPrice: 8.90,
    totalValue: 400.50,
    expiryDate: "2026-07-28", // <4 days
    location: "Cold Storage Room C",
    supplier: "Prime Cut Meats",
    status: "warning",
    isDispatched: false,
  },
  {
    id: "INV-8095",
    sku: "PH-2201",
    name: "Vitamin C Supplement 1000mg",
    category: "Pharmaceuticals",
    quantity: 120,
    unit: "Bottles",
    unitPrice: 14.50,
    totalValue: 1740,
    expiryDate: "2026-07-31", // <7 days
    location: "Pharma Shelf 3",
    supplier: "MediHealth Labs",
    status: "warning",
    isDispatched: false,
  },
  {
    id: "INV-8096",
    sku: "PT-7782",
    name: "Organic Tomato Puree 400g",
    category: "Pantry & Canned",
    quantity: 310,
    unit: "Cans",
    unitPrice: 1.95,
    totalValue: 604.50,
    expiryDate: "2026-08-15", // >15 days
    location: "Main Warehouse Shelf B2",
    supplier: "SunRipe Foods",
    status: "safe",
    isDispatched: false,
  },
  {
    id: "INV-8097",
    sku: "DY-4419",
    name: "Greek Yogurt Vanilla 500g",
    category: "Dairy & Eggs",
    quantity: 95,
    unit: "Tubs",
    unitPrice: 4.20,
    totalValue: 399,
    expiryDate: "2026-07-29",
    location: "Cold Unit 1",
    supplier: "Alpine Dairy",
    status: "warning",
    isDispatched: false,
  },
  {
    id: "INV-8098",
    sku: "PR-8820",
    name: "Baby Spinach Leaves 250g",
    category: "Fresh Produce",
    quantity: 70,
    unit: "Bags",
    unitPrice: 3.10,
    totalValue: 217,
    expiryDate: "2026-07-26",
    location: "Produce Bay 3",
    supplier: "Fresh Harvest Co",
    status: "critical",
    isDispatched: false,
  },
];

export const MOCK_NGOS: NGO[] = [
  {
    id: "NGO-101",
    name: "Metro Harvest Food Bank",
    category: "Food Bank",
    contactPerson: "Sarah Jenkins",
    email: "s.jenkins@metroharvest.org",
    phone: "+1 (555) 234-8901",
    location: "Downtown District, Zone 4",
    verified: true,
    activeDispatches: 3,
    totalRescuedKg: 14250,
    capacityLevel: "High",
    hasColdStorage: true,
    rating: 4.9,
    avatarUrl: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "NGO-102",
    name: "Hope Shelter & Community Kitchen",
    category: "Community Kitchen",
    contactPerson: "David Miller",
    email: "dmiller@hopeshelter.org",
    phone: "+1 (555) 876-5432",
    location: "Eastside Hub, Zone 2",
    verified: true,
    activeDispatches: 1,
    totalRescuedKg: 9800,
    capacityLevel: "Medium",
    hasColdStorage: true,
    rating: 4.8,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "NGO-103",
    name: "Nourish Family Network",
    category: "Shelter",
    contactPerson: "Elena Rostova",
    email: "elena@nourishnet.org",
    phone: "+1 (555) 432-1098",
    location: "North Suburbs, Zone 1",
    verified: true,
    activeDispatches: 0,
    totalRescuedKg: 6400,
    capacityLevel: "High",
    hasColdStorage: false,
    rating: 4.7,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "NGO-104",
    name: "PharmaRelief Global",
    category: "Medical Aid",
    contactPerson: "Dr. Marcus Vance",
    email: "m.vance@pharmarelief.org",
    phone: "+1 (555) 901-2345",
    location: "Medical Center Drive",
    verified: true,
    activeDispatches: 2,
    totalRescuedKg: 3100,
    capacityLevel: "Medium",
    hasColdStorage: true,
    rating: 5.0,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "CUST-301",
    name: "GreenGrocer Marketplaces",
    type: "Supermarket Chain",
    contactName: "Robert Sterling",
    email: "r.sterling@greengrocer.com",
    phone: "+1 (555) 678-9012",
    totalItemsDonated: 4820,
    totalValueSaved: 38450,
    impactScore: 98,
    tier: "Platinum",
    joinDate: "2025-01-15",
    status: "Active",
  },
  {
    id: "CUST-302",
    name: "Apex Foods Wholesale",
    type: "Wholesale Distributor",
    contactName: "Amanda Chen",
    email: "achen@apexfoods.io",
    phone: "+1 (555) 345-6789",
    totalItemsDonated: 3150,
    totalValueSaved: 26900,
    impactScore: 92,
    tier: "Gold",
    joinDate: "2025-03-10",
    status: "Active",
  },
  {
    id: "CUST-303",
    name: "Sunnyside Farm Fresh",
    type: "Local Organic Market",
    contactName: "Liam O'Connor",
    email: "liam@sunnysidefresh.com",
    phone: "+1 (555) 789-0123",
    totalItemsDonated: 1890,
    totalValueSaved: 14200,
    impactScore: 86,
    tier: "Silver",
    joinDate: "2025-06-01",
    status: "Active",
  },
  {
    id: "CUST-304",
    name: "CarePlus Pharmacy Group",
    type: "Pharmacy Chain",
    contactName: "Patricia Brooks",
    email: "p.brooks@careplus.org",
    phone: "+1 (555) 890-1234",
    totalItemsDonated: 2400,
    totalValueSaved: 42100,
    impactScore: 95,
    tier: "Platinum",
    joinDate: "2025-02-20",
    status: "Active",
  },
];

export const MOCK_TRENDS: ExpiryTrendData[] = [
  { month: "Feb", rescued: 1200, waste: 180, valueSaved: 14200 },
  { month: "Mar", rescued: 1850, waste: 140, valueSaved: 19800 },
  { month: "Apr", rescued: 2300, waste: 110, valueSaved: 24500 },
  { month: "May", rescued: 3100, waste: 95, valueSaved: 32100 },
  { month: "Jun", rescued: 3900, waste: 70, valueSaved: 41200 },
  { month: "Jul", rescued: 4850, waste: 45, valueSaved: 51800 },
];

export const MOCK_CATEGORY_BREAKDOWN: CategoryBreakdown[] = [
  { name: "Fresh Produce", value: 38, color: "#10b981" },
  { name: "Dairy & Eggs", value: 24, color: "#3b82f6" },
  { name: "Bakery & Deli", value: 18, color: "#f59e0b" },
  { name: "Pharmaceuticals", value: 12, color: "#8b5cf6" },
  { name: "Meat & Seafood", value: 8, color: "#f43f5e" },
];

export const MOCK_ACTIVITIES: ActivityLog[] = [
  {
    id: "ACT-1",
    title: "140 Milk Cartons Dispatched to Metro Harvest",
    timestamp: "12 mins ago",
    type: "dispatch",
    description: "Item SKU #DY-9921 rescued & claimed by Sarah Jenkins.",
    actor: "Dispatch System",
  },
  {
    id: "ACT-2",
    title: "Critical Expiry Alert: Hass Avocados",
    timestamp: "1 hour ago",
    type: "alert",
    description: "85 Packs expiring in 3 days. Automated NGO alert sent.",
    actor: "Smart Tracker",
  },
  {
    id: "ACT-3",
    title: "New Wholesale Supplier Onboarded",
    timestamp: "3 hours ago",
    type: "customer",
    description: "Apex Foods Wholesale activated Platinum Impact Tier.",
    actor: "Admin Team",
  },
  {
    id: "ACT-4",
    title: "60 Sourdough Loaves Swapped",
    timestamp: "5 hours ago",
    type: "swap",
    description: "Successfully transferred to Hope Shelter Community Kitchen.",
    actor: "Hope Shelter Rep",
  },
];
